name: Release

on:
  release:
    types: [ published ]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Lester-VER2.0.exe
        uses: actions/download-artifact@v4
        with:
          name: Lester-VER2.0.exe

      - name: Upload Artifacts to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: Lester-VER2.0.exe
          allowUpdates: true
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true